$schema: http://json-schema.org/draft-04/schema#

type: object
properties:
  inputs:
    type: object
    required:
      - json

    properties:
      json:
        anyOf:
          - type: string
          - type: object
          - type: array

  outputs:
    type: object
    additionalProperties:
      anyOf:
         - type: string
         - type: number
