language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby-9.0.0.0
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-9.0.0.0
    - rvm: rbx-2
  fast_finish: true
script: bundle exec rake
before_install:
  - gem update --system
  - gem update bundler
services:
  - redis-server
branches:
  except:
    - /^v[0-9]/
notifications:
  email: false
  webhooks:
    urls:
      - https://lita-freenode.herokuapp.com/travis
