image: ruby:2.3.1

services:
  - redis:latest
  - postgres:latest

variables:
  POSTGRES_DB: mr_markov_test
  POSTGRES_USER: postgres
  RACK_RNV: test

before_script:
  - gem install bundler
  - bundle install --path /cache/.gems
  - bundle exec rake db:migrate RACK_ENV=test

test:
  stage: test
  script: bundle exec rake test

  artifacts:
    paths:
      - coverage/

docs:
  stage: test
  script: bundle exec rake yard

  artifacts:
    paths:
    - docs/
